### ISSUE TITLE
New way for customizing 1D2D connections and breaches

### ISSUE THREAD

**Issue by caspervdw** [nens/threedigrid-builder#129]
In #80 the (old) way of specifying 1D2D connection was re implemented. While doing that, @martijn-siemerink had some thoughs of making this more user friendly:

- user should supply a line instead of 2 points (so 1 table instead of 2)
- the idea is that only the custom 1D2D lines are provided, the default ones should not (as is done now)
- the 1D end of the line is connected to a user-supplied object id and type (as it is now)
- the 1D end of the line should *spatially* snap to the closest (interpolated) node, this would give more stable results than the node_number approach we have now
- (suggestion by Leendert) add discharge coefficients to enable single-directional flow

**Comment by Jonasvsl** [comment]
Related to https://github.com/nens/threedi-api/issues/1476
