### ISSUE TITLE
Improvements manholes/connection_nodes.

### ISSUE THREAD

**Issue by martijn-siemerink** [nens/threedigrid-builder#227]
- [ ] Set calculation_type on v2_connection_nodes.
- [ ] Node type is dependent on manhole table and not storage_area of connection_node.
- [ ] Connecting 1D2D flow line kcu type dependent on manhole table and not storage_area of connection_node.
- [ ] Use of drain_level dependent on manhole_table and not storage_area of connection_node.

**Comment by leendertvanwolfswinkel** [comment]
Is included in 1D migration
