### ISSUE TITLE
Raise SchematisationError als refinement_levels > kmax

### ISSUE THREAD

**Issue by martijn-siemerink** [nens/threedigrid-builder#254]
Wanneer een model refinement geometrieën bevat met refinement levels groter dan kmax, moeten we SchematisationError raisen.

Voorbeeld model waar dit gebeurd:

https://api.3di.live/v3/threedimodels/49433/

**Comment by caspervdw** [comment]
Covered in modelchecker already. https://github.com/nens/threedi-modelchecker/issues/204
