### ISSUE TITLE
Support conveyance in threedigrid-builder

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedigrid-builder#330]
Currently, we have two friction types, Chézy (1) or Manning (2)

Two new friction types will be introduced for 1D:
- Chézy with conveyance (3) 
- Manning with conveyance (4)	

These friction types are valid only for cross sections that meet the following criteria:
- Tabulated rectangle, tabulated trapezium, or YZ 
- At each higher height, the width stays the same or increases (>=). I.e. the cross-section never becomes narrower when going up. 
These criteria will be checked in `threedi-modelchecker`. 

If users assigned friction type 3 or 4, the flowlines's attribute **frict1d** should be set to **Chézy_conveyance** or **Manning_conveyance** respectively.

**Comment by leendertvanwolfswinkel** [comment]
@nvolp please edit the ticket description to your liking and fill in the XXX's

**Comment by GolnesaK** [comment]
After we have made the final design of ticket number , the xxx will be named.

**Comment by caspervdw** [comment]
I think this is about 3 days work in total (including modelchecker stuff), provided that all details are filled in.

I removed myself as assignee because I am going on holiday and it is in the sprint backlog. @elisallenens supported by @daanvaningen could maybe do this in my absence.
