### ISSUE TITLE
Obstacle height not prioritized for exchange levels in same cell 1D-2D Single connected lines with storage. TOPDESK 23070061

### ISSUE THREAD

**Issue by PySjon** [nens/threedigrid-builder#332]
### Contact Details

sjon.vandijk@nelen-schuurmans.nl

### Complexity

complex

### Priority

high prio

### What happened?

When building the 3Di calculation grid, the 1D/2D connection lines should adopt the obstacle height as exchange level height (if obstacle height > connection line exchange level). This works for flowlines crossing cells. Yet for 1D/2D connection lines within a cell (so begin and endpoint are within the same cell) this doesn't seem to be the case. The exchange levels are not adjusted and water flows straight through the obstacle. 

### How to Reproduce?

1. Take this model: https://management.3di.live/schematisations/6887/49816
2. Generate the calculation grid.
3. Look at the 1D/2D exchange line crossing the obstacle code 'LEV-WIETSE-08' near orifice 'KDU-Q-1991, exchange line code 28784 (calculation node start 3518, calculation node end 12048).
4. See how they do not adopt the obstacle crest level (0.41m) but remain unchanged (-0.65m). 

### What did you expect and what was the actual result?

I expected (1) new exchange levels and thus (2) results where water would not flow through this flowline. 
Yet it didn't and it did (funny sentence). 

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.
![image](https://github.com/nens/threedigrid-builder/assets/46816504/66d651ff-957d-4594-be64-ff830f7a50a0)

### Additional info
@leendertvanwolfswinkel It seems I can't assign it to you, so I tagged you.

**Comment by daanvaningen** [comment]
Leendert ik heb in mijn mail geen reply van jou kunnen vinden op dit ticket dus denk dat daar iets mis is gegaan. Kan jij wat je hebt gestuurd nog ergens in je verzonden berichten vinden?
