### ISSUE TITLE
YZ profile with variable friction

### ISSUE THREAD

**Issue by GolnesaK** [nens/threedigrid-builder#342]
- Transfer YZ profiles for open channel as coordinate pairs to the core
- Define a 2D array consisting of 4 columns; (:,1:2) is the (y,z) coordinates, (:,3) is friction values, and (:,4) is vegetation data
- y component must be in increasing manner
- Make correction to the cross-section by removing the short lines, or do this as a "check" to prevent users from defining lines shorter than a "user-defined/default" value

**Comment by GolnesaK** [comment]
Instead of last item indicated in the description, simplify the whole cross-section unless different roughness/vegetation properties are assigned to different lines.
In cross-section simplification, the topology must be reserved and it should include: removing short lines, merging two succeeding lines of the same slope

**Comment by daanvaningen** [comment]
api is still on 1.12.2
