### ISSUE TITLE
Make gridbuilder compatible with numpy 2.0

### ISSUE THREAD

**Issue by margrietpalm** [nens/threedigrid-builder#369]

**Comment by elisalle** [comment]
Looked at this with Casper and since GDAL does not support numpy 2, we currently cannot either.

**Comment by margrietpalm** [comment]
Should we than fix the numpy version to <2.0? @leendertvanwolfswinkel @caspervdw

**Comment by elisalle** [comment]
Numpy 2.0 support has now been added in #372 .
